version: "3"
vars:
  SERVICE_NAME: frontend
  NAMESPACE: flags-gg
tasks:
  make-temp-files:
    cmds:
      - task: get-latest-tag
      - task: get-commit-hash
  get-latest-tag:
    cmds:
      - |
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        if [[ -z "$latest_tag" ]]; then
          echo "0.0.1" > .latest_tag
        else
          echo $latest_tag | awk -F. '{printf "%d.%d.%d", $1, $2, $3}' > .latest_tag
        fi
    silent: true
  get-commit-hash:
    cmd: git rev-parse --short HEAD > .commit_hash
    silent: true
  clean-git-file:
    cmds:
      - rm .latest_tag
      - rm .commit_hash
  test:
    cmd: npm test

  # Publish Commands
  publish-images:
    cmds:
      - task: get-commit-hash
        vars:
          COMMIT_HASH:
            sh: cat .commit_hash
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} --all-platforms
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest --all-platforms
    vars:
      COMMIT_HASH:
        sh: cat .commit_hash

  # Build Commands
  build-images:
    cmds:
      - task: get-latest-tag
        vars:
          LATEST_TAG:
            sh: cat .latest_tag
      - task: get-commit-hash
        vars:
          COMMIT_HASH:
            sh: cat .commit_hash
      - |
        nerdctl build \
          --platform=amd64,arm64 \
          --tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} \
          --build-arg GIT_VERSION={{.LATEST_TAG}} \
          --build-arg GIT_BUILD={{.COMMIT_HASH}} \
          --build-arg SERVICE_NAME={{.SERVICE_NAME}} \
          --build-arg KEYCLOAK_SECRET={{.KEYCLOAK_SECRET}} \
          --build-arg FLAGS_API_SERVER="https://api.flags.gg/v1" \
          --build-arg FLAGS_COMPANY_ID=85ccae4e-7bb3-4ec5-bfc7-b08a80e59328 \
          --build-arg FLAGS_AGENT_ID=c778cf4b-83f1-4c53-951e-604102c84898 \
          --build-arg FLAGS_ENVIRONMENT_ID=81aca98e-3b01-4c3c-a4cf-c7eee26185c5 \
          -f ./k8s/Containerfile .
      - nerdctl tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest
    vars:
      LATEST_TAG:
        sh: cat .latest_tag
      COMMIT_HASH:
        sh: cat .commit_hash
      KEYCLOAK_SECRET:
        sh: cat keycloak.secret
  build-push-latest:
    cmds:
      - task: get-latest-tag
      - task: get-commit-hash
      - nerdctl build --platform=amd64,arm64 --tag containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest --build-arg VERSION={{.LATEST_TAG}} --build-arg BUILD={{.COMMIT_HASH}} --build-arg SERVICE_NAME={{.SERVICE_NAME}} --build-arg KEYCLOAK_SECRET={{.KEYCLOAK_SECRET}} -f ./k8s/Containerfile .
      - nerdctl push containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest --all-platforms
    vars:
      LATEST_TAG:
        sh: cat .latest_tag
      COMMIT_HASH:
        sh: cat .commit_hash
      KEYCLOAK_SECRET:
        sh: cat keycloak.secret

  build:
    cmds:
      - task: build-images

  # Deploy Commands
  deploy:
    cmd: kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.COMMIT_HASH}} -n {{.NAMESPACE}}
    vars:
      COMMIT_HASH:
        sh: cat .commit_hash
  deploy-latest:
    cmds:
      - kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:latest -n {{.NAMESPACE}}
      - kubectl rollout restart deployment/{{.SERVICE_NAME}} -n {{.NAMESPACE}}
  deploy-latest-tag:
    cmds:
      - kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.LATEST_TAG}} -n {{.NAMESPACE}}
      - kubectl rollout restart deployment/{{.SERVICE_NAME}} -n {{.NAMESPACE}}
    vars:
      LATEST_TAG:
        sh: cat .latest_tag

  # Extras
  build-deploy:
    cmds:
      - task: build-images
      - task: publish-images
      - task: deploy
  build-deploy-latest:
     cmds:
      - task: build-push-latest
      - task: deploy-latest
