# Base
FROM containers.chewed-k8s.net/docker_hub_cache/library/node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

## Copy the files
WORKDIR /frontend
COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY public ./public
COPY src ./src
COPY public ./public
COPY tsconfig.json ./

# Install dependencies
FROM base AS dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --production

# Build
FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
ARG KEYCLOAK_SECRET
ENV REACT_APP_KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
RUN pnpm build

# Runner
FROM containers.chewed-k8s.net/docker_hub_cache/library/node:20-alpine AS runner
WORKDIR /runner
COPY --from=build /frontend/build /runner
RUN npm install -g serve

ARG BUILD
ARG VERSION
ENV REACT_APP_COMMIT_HASH=${BUILD}
ENV REACT_APP_GIT_TAG=${VERSION}

CMD ["serve", "-s", "/runner", "-l", "80"]
