---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flags-gg
  labels:
    name: frontend
    app: frontend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
        app: frontend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: frontend
          image: containers.chewed-k8s.net/flags-gg/frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: REACT_APP_KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: keycloak-client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flags-gg
  labels:
    name: frontend
    app: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: flags-gg
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: frontend
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - flags.gg
        - www.flags.gg
      secretName: frontend-tls
  rules:
    - host: flags.gg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.flags.gg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
