---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flags-gg
  labels:
    name: frontend
    app: frontend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
        app: frontend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: frontend
          image: containers.chewed-k8s.net/flags-gg/frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: VITE_KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: keycloak-client-secret
            - name: VITE_FLAGS_API_SERVER
              value: "https://api.flags.gg/v1"
            - name: VITE_FLAGS_COMPANY_ID
              value: "85ccae4e-7bb3-4ec5-bfc7-b08a80e59328"
            - name: VITE_FLAGS_DASHBOARD_ID
              value: "c778cf4b-83f1-4c53-951e-604102c84898"
            - name: VITE_FLAGS_DASHBOARD_ENVIRONMENT_ID
              value: "81aca98e-3b01-4c3c-a4cf-c7eee26185c5"
            - name: VITE_FLAGS_FRONTEND_ID
              value: "a7978e82-bee0-4357-808d-53ee33d3bc55"
            - name: VITE_FLAGS_FRONTEND_ENVIRONMENT_ID
              value: "f8f84114-0706-40b7-a929-995d675f1f6d"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flags-gg
  labels:
    name: frontend
    app: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: flags-gg
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: frontend
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - flags.gg
        - www.flags.gg
      secretName: frontend-tls
  rules:
    - host: flags.gg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.flags.gg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
